version: '3.1'

services:
  # Database
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # Api HTTP client
  twitch-bot:
    build:
      context: ./twitch-bot
      dockerfile: Dockerfile-dev
    volumes:
      - ./twitch-bot:/app